import type { ImageKey } from "./images";

export const photographers = [
  {
    id: 1,
    name: "Adaeze Okafor",
    specialty: "Portrait & Fashion",
    avatar: "portrait-woman-5" as ImageKey,
    cover: "fashion-1" as ImageKey,
    followers: "48.2K",
    rating: 4.9,
    reviews: 124,
    city: "Lagos",
    location: "Lagos, Nigeria",
    available: true,
    priceHourly: 45_000,
    bio: "Award-winning portrait and fashion photographer with 10+ years of experience across Lagos, Abuja, and Accra, working with leading African brands and editorial houses.",
  },
  {
    id: 2,
    name: "Emeka Nwosu",
    specialty: "Wedding & Events",
    avatar: "portrait-man-1" as ImageKey,
    cover: "wedding-1" as ImageKey,
    followers: "31.7K",
    rating: 4.8,
    reviews: 89,
    city: "Abuja",
    location: "Abuja, Nigeria",
    available: true,
    priceHourly: 35_000,
    bio: "Documentary wedding photographer capturing authentic emotion at ceremonies across Nigeria and West Africa for the past eight years.",
  },
  {
    id: 3,
    name: "Zara Okonkwo",
    specialty: "Street & Documentary",
    avatar: "portrait-woman-1" as ImageKey,
    cover: "street-1" as ImageKey,
    followers: "62.1K",
    rating: 5.0,
    reviews: 201,
    city: "Lagos",
    location: "Lagos, Nigeria",
    available: false,
    priceHourly: 55_000,
    bio: "Documentary photographer capturing raw human moments across Nigeria and the continent. World Press Photo finalist 2024.",
  },
  {
    id: 4,
    name: "Kunle Bakare",
    specialty: "Nature & Landscape",
    avatar: "portrait-man-3" as ImageKey,
    cover: "nature-1" as ImageKey,
    followers: "89.4K",
    rating: 4.9,
    reviews: 178,
    city: "Ibadan",
    location: "Ibadan, Nigeria",
    available: true,
    priceHourly: 30_000,
    bio: "Landscape photographer exploring Nigeria's coastlines, savannah, and city skylines with a minimalist, atmospheric style.",
  },
  {
    id: 5,
    name: "Amara Eze",
    specialty: "Fashion & Lifestyle",
    avatar: "portrait-woman-2" as ImageKey,
    cover: "lifestyle-1" as ImageKey,
    followers: "74.8K",
    rating: 4.8,
    reviews: 156,
    city: "Port Harcourt",
    location: "Port Harcourt, Nigeria",
    available: true,
    priceHourly: 42_000,
    bio: "Fashion and lifestyle photographer collaborating with Nigerian designers, beauty brands, and creative directors nationwide.",
  },
  {
    id: 6,
    name: "James Obi",
    specialty: "Corporate & Branding",
    avatar: "portrait-man-2" as ImageKey,
    cover: "corporate-1" as ImageKey,
    followers: "22.3K",
    rating: 4.7,
    reviews: 67,
    city: "Lagos",
    location: "Lagos, Nigeria",
    available: true,
    priceHourly: 28_000,
    bio: "Corporate and brand photographer specializing in executive portraits, team shoots, and product campaigns for Nigerian businesses.",
  },
] as const;

export const categories = [
  { name: "Wedding", count: "12.4K photos", image: "wedding-2" as ImageKey },
  { name: "Portrait", count: "28.1K photos", image: "portrait-woman-5" as ImageKey },
  { name: "Street", count: "9.7K photos", image: "street-1" as ImageKey },
  { name: "Nature", count: "34.2K photos", image: "nature-1" as ImageKey },
  { name: "Fashion", count: "15.8K photos", image: "fashion-1" as ImageKey },
  { name: "Corporate", count: "7.3K photos", image: "corporate-1" as ImageKey },
  { name: "Lifestyle", count: "19.6K photos", image: "lifestyle-1" as ImageKey },
  { name: "Events", count: "11.2K photos", image: "events-1" as ImageKey },
] as const;

export const marketplaceItems = [
  { id: 1, title: "Golden Hour Cityscape", priceAmount: 3_500, image: "street-1" as ImageKey, seller: "Emeka Nwosu", downloads: 847, rating: 4.8, category: "Street" },
  { id: 2, title: "Ethereal Portrait Series", priceAmount: 5_000, image: "portrait-woman-5" as ImageKey, seller: "Adaeze Okafor", downloads: 1204, rating: 4.9, category: "Portrait" },
  { id: 3, title: "Forest Morning Light", priceAmount: 7_500, image: "nature-1" as ImageKey, seller: "Kunle Bakare", downloads: 563, rating: 5.0, category: "Nature" },
  { id: 4, title: "Urban Geometry Pack", priceAmount: 12_000, image: "corporate-1" as ImageKey, seller: "Zara Okonkwo", downloads: 921, rating: 4.7, category: "Street" },
  { id: 5, title: "Wedding Moments Vol.2", priceAmount: 18_500, image: "wedding-1" as ImageKey, seller: "Emeka Nwosu", downloads: 334, rating: 4.9, category: "Wedding" },
  { id: 6, title: "High Fashion Editorial", priceAmount: 15_000, image: "fashion-2" as ImageKey, seller: "Amara Eze", downloads: 678, rating: 4.8, category: "Fashion" },
  { id: 7, title: "Corporate Excellence", priceAmount: 4_500, image: "corporate-2" as ImageKey, seller: "James Obi", downloads: 412, rating: 4.6, category: "Corporate" },
  { id: 8, title: "Nature's Symphony", priceAmount: 9_000, image: "nature-2" as ImageKey, seller: "Kunle Bakare", downloads: 789, rating: 5.0, category: "Nature" },
] as const;

export const testimonials = [
  {
    name: "Ngozi Adebayo",
    role: "Creative Director, Lagos Fashion Week",
    avatar: "portrait-woman-3" as ImageKey,
    text: "UJAS PhotoHub transformed how we discover talent. The quality here is unmatched — we've found three cover photographers through this platform alone.",
    rating: 5,
  },
  {
    name: "Tunde Williams",
    role: "Wedding Client, Lagos",
    avatar: "portrait-man-1" as ImageKey,
    text: "Booked Adaeze Okafor for our wedding and the results were beyond our dreams. The booking process was seamless and the final photos are absolutely stunning.",
    rating: 5,
  },
  {
    name: "Chioma Nwachukwu",
    role: "Fashion Brand Owner, Abuja",
    avatar: "portrait-woman-4" as ImageKey,
    text: "The marketplace is incredible. We license photos for our campaigns directly through the platform and save days of back-and-forth negotiations.",
    rating: 5,
  },
] as const;

export const portfolioImages: { id: ImageKey; h: number }[] = [
  { id: "portrait-woman-5", h: 280 },
  { id: "fashion-1", h: 360 },
  { id: "lifestyle-1", h: 240 },
  { id: "wedding-1", h: 320 },
  { id: "nature-1", h: 270 },
  { id: "street-1", h: 300 },
  { id: "corporate-1", h: 250 },
  { id: "events-1", h: 340 },
  { id: "portfolio-1", h: 260 },
];
